parameters:
- name: artifactStagingDirectory
  type: string
  default: 
- name: sourceFolder
  type: string
  default: 
- name: artifactName
  type: string
  default: 
- name: helmVersion
  type: string
  default: 
- name: chartPath
  type: string
  default: 

steps:
- task: Tokenizer@0
  displayName: 'Tokenizer to set build number in values.release.yaml'
  inputs:
    sourceFilesPattern: 'values.release.yaml'
    sourcePath: ${{ parameters.sourceFolder }}

- task: CopyFiles@2
  displayName: 'Copy Files to:${{ parameters.artifactStagingDirectory }}/${{ parameters.artifactName }}'
  inputs:
    SourceFolder: ${{ parameters.sourceFolder }}
    Contents: values.release.yaml
    TargetFolder: '${{ parameters.artifactStagingDirectory }}/${{ parameters.artifactName }}'

- task: HelmInstaller@0
  displayName: 'Install Helm ${{ parameters.helmVersion }}'
  inputs:
    helmVersion: '${{ parameters.helmVersion }}'
    checkLatestHelmVersion: false
    installKubectl: true

- task: HelmDeploy@0
  displayName: 'helm package'
  inputs:
    azureSubscription: $(AzureSubscription)
    azureResourceGroup: $(AzureResourceGroup)
    kubernetesCluster: $(KubernetesCluster)
    command: package
    chartPath: ${{ parameters.chartPath }}
    destination: '${{ parameters.artifactStagingDirectory }}/${{ parameters.artifactName }}'
    chartVersion: '$(Build.BuildNumber)'
    save: false
    
- publish: '${{ parameters.artifactStagingDirectory }}/${{ parameters.artifactName }}'
  artifact: '${{ parameters.artifactName }}'
  displayName: 'Publish Artifact: ${{ parameters.artifactName }}'