replicaCount: __ReplicaCount__

image:
  repository: __ImageName__
  tag: __Build.BuildNumber__

ingress:
  hosts:
    - __IngressHostName__
  tls:
    - secretName: __TlsSecretName__
      hosts:
        - __IngressHostName__

envvariables:
  applicationinsights__instrumentationkey: __InstrumentationKey__
  devfunoptions__url: __ServiceUrl__
  devfunoptions__deploymentenvironment: __DeploymentEnvironment__
  devfunoptions__alternatetestingurl: __AlternateTestingUrl__
  devfunoptions__flagenablealternateurl: "__FlagEnableAlternateUrl__"

explicitCertIssuer: __CertIssuer__