# Default values for devfunweb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
fullnameOverride: devfunweb
replicaCount: 2
image:
  repository: VALUE_TO_BE_OVERRIDDEN
  tag: latest

imagePullSecrets:
  - name: acrauth
  # Optionally specify an array of imagePullSecrets.
  # Secrets must be manually created in the namespace.
  # ref: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
  #
  # This uses credentials from secret "myRegistryKeySecretName".
  # - name: myRegistryKeySecretName
service:
  type: ClusterIP
  port: 80

deployment:
  containerPort: 8080

probes:
  enabled: true

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - www.dev.devfun.4tecture.ch
  tls:
    - secretName: wwwdevfun-tls
      hosts:
        - www.dev.devfun.4tecture.ch

secrets: {}
  # Optionally specify a set of secret objects whose values
  # will be injected as environment variables by default.
  # You should add this section to a file like secrets.yaml
  # that is explicitly NOT committed to source code control
  # and then include it as part of your helm install step.
  # ref: https://kubernetes.io/docs/concepts/configuration/secret/
  #
  # This creates a secret "mysecret" and injects "mypassword"
  # as the environment variable MYSECRET_MYPASSWORD=123.
  # mysecret:
  #   mypassword: 123

envvariables:
  applicationinsights__instrumentationkey: VALUE_TO_BE_OVERRIDDEN
  devfunoptions__url: VALUE_TO_OVERRIDE
  devfunoptions__deploymentenvironment: VALUE_TO_OVERRIDE
  devfunoptions__alternatetestingurl: VALUE_TO_OVERRIDE
  devfunoptions__flagenablealternateurl: VALUE_TO_OVERRIDE

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
nodeSelector: {}

tolerations: []

affinity: {}

explicitCertIssuer: VALUE_TO_OVERRIDE

workloadIdentity:
  enabled: false
  provider: "Azure"  # Options: "Azure", "AWS", "GCP"
  azure:
    clientId: "VALUE_TO_OVERRIDE"
    name: "VALUE_TO_OVERRIDE"
    tenantId: ""  # Optional: Provide if needed