apiVersion: v1
kind: ServiceAccount
metadata:
  name: devfunweb-service-account
  {{- if and .Values.workloadIdentity.enabled (eq .Values.workloadIdentity.provider "Azure") }}
  annotations:
    azure.workload.identity/client-id: "{{ .Values.workloadIdentity.azure.clientId }}"
    {{- if .Values.workloadIdentity.azure.tenantId }}
    azure.workload.identity/tenant-id: "{{ .Values.workloadIdentity.azure.tenantId }}"
    {{- end }}
  {{- end }}