apiVersion: v1
kind: ServiceAccount
metadata:
  name: devfunapi-service-account
  {{- if and .Values.workloadIdentity.enabled (eq .Values.workloadIdentity.provider "Azure") }}
  annotations:
    azure.workload.identity/client-id: "{{ .Values.workloadIdentity.azure.clientId }}"
    {{- if .Values.workloadIdentity.azure.tenantId }}
    azure.workload.identity/tenant-id: "{{ .Values.workloadIdentity.azure.tenantId }}"
    {{- end }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devfunapi-deploy-service-account
  {{- if and .Values.deployworkloadIdentity.enabled (eq .Values.deployworkloadIdentity.provider "Azure") }}
  annotations:
    azure.workload.identity/client-id: "{{ .Values.deployworkloadIdentity.azure.clientId }}"
    {{- if .Values.deployworkloadIdentity.azure.tenantId }}
    azure.workload.identity/tenant-id: "{{ .Values.deployworkloadIdentity.azure.tenantId }}"
    {{- end }}
  {{- end }}