trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: Gitleaks@2
  inputs:
    scanlocation: '$(Build.SourcesDirectory)'
    configtype: 'predefined'
    predefinedconfigfile: 'GitleaksUdmCombo.toml'
    ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
      scanmode: 'prevalidation'
    ${{ else }}:
      scanmode: 'smart'
    reportformat: 'sarif'
    